bookmark/urls.py
from django.urls import path
from .views import BookmarkCreateView, BookmarkDeleteView, BookmarkDetailView, \
        BookmarkListView, BookmarkUpdateView

app_name = 'bookmark'
urlpatterns = [
    path('', BookmarkListView.as_view(), name='list'),
    path('add/', BookmarkCreateView.as_view(), name='add'),
    path('detail/<int:pk>', BookmarkDetailView.as_view(), name='detail'),
    path('update/<int:pk>', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BookmarkDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
    path('', include('board.urls')),
    path('photo/', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
    path('deallist/', include('deallist.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('board/', include('board.urls')),
    path('todo/', include('todo.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL) 

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path('', views.Todo_ListView.as_view(), name='plist'),
    path('list/<int:pcode>', views.Todo_ListView.as_view(), name='list'),
    path('insert/<int:pcode>', views.check_post, name='insert'),
    path('save_priority/', views.save_priority, name='save_priority'),
    path('is_complete/', views.is_complete, name='is_complete'),
    path('is_non_complete/', views.is_non_complete, name='is_non_complete'),
    path('detail/<int:pk>', views.Todo_DetailView.as_view(), name='detail'),
    path('update/<int:pk>', views.Todo_UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.Todo_DeleteView.as_view(), name='delete'),
]

bookmark/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Bookmark(models.Model):
    site_name = models.CharField(max_length=100)
    url = models.URLField('Site URL')

    def __str__(self):
        return self.site_name+" "+self.url

    def get_absolute_url(self):
        return reverse("detail", args=[str(self.id)])

bookmark/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy

from .models import Bookmark


# Create your views here.
class BookmarkListView(ListView):
    model = Bookmark
    paginate_by = 5
    ordering = "-id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if context['is_paginated']:
            context["min_page"] = min(context['page_obj'].number - 5, context['page_obj'].paginator.num_pages - 10)
            context["max_page"] = max(context['page_obj'].number + 5, 11)
        return context

class BookmarkCreateView(CreateView):
    model = Bookmark
    fields = ['site_name', 'url']
    success_url = reverse_lazy('bookmark:list')
    template_name_suffix = '_create'

class BookmarkDetailView(DetailView):
    model = Bookmark

class BookmarkUpdateView(UpdateView):
    model = Bookmark
    fields = ['site_name', 'url']
    template_name_suffix = '_update'

class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:list')

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <div class="alert alert-danger">Do you want to delete Bookmark "{{object}}"?</div>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock content %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}

{% block title %}Bookmark Add{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="add" class="btn btn-info btn-sm">
    </form>
{% endblock content %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock %}

{% block content %}
    {{ object.site_name }}<br />
    {{ object.url }}
{% endblock content %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}Bookmark List{% endblock %}

{% block content %}
    <div class="btn-group">
        <a href="{% url 'bookmark:add' %}" class="btn btn-info">Add Bookmark</a>
    </div>
    <table class="table">
        <thead>
            <tr>                
                <th scope="col">#</th>
                <th scope="col">Site</th>
                <th scope="col">URL</th>
                <th scope="col">Modify</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for bookmark in object_list %}
                <tr>
                    <td>{{ bookmark.id }}</td>
                    <td><a href="{% url 'bookmark:detail' pk=bookmark.id %}">{{ bookmark.site_name }}</a></td>
                    <td><a href="{{ bookmark.url }}" target="_blank">{{ bookmark.url }}</a></td>
                    <td><a href="{% url 'bookmark:update' pk=bookmark.id %}" class="btn btn-success btn-sm">Modify</a></td>
                    <td><a href="{% url 'bookmark:delete' pk=bookmark.id %}" class="btn btn-danger btn-sm">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block pagination %}
    {% include 'pagination.html' %}
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block title %}Bookmark Modify{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" class="btn btn-info btn-sm">
    </form>
{% endblock content %}