board/urls.py
from django.urls import path

from . import views

app_name = 'board'
urlpatterns = [
    path('', views.home, name='home'),
    path('boards/<slug:board_slug>/', views.post_list, name='post_list'),
    path('boards/<slug:board_slug>/<slug:appr_type>/', views.post_list, name='appr_list'),
    path('boards/<slug:board_slug>/posts/new/', views.new_post, name='new_post'),
    path('posts/<int:post_id>/', views.view_post, name='view_post'),
    path('posts/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('posts/<int:post_id>/like/', views.like_post, name='like_post'),
    path('posts/<int:post_id>/edit/', views.edit_post, name='edit_post'),
    path('posts/<int:post_id>/history/', views.post_history_list, name='post_history_list'),
    path('posts/<int:post_id>/comments/', views.comment_list, name='comment_list'),
    path('posts/<int:post_id>/comments/new/', views.new_comment, name='new_comment'),
    path('posts/<int:post_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('posts/<int:post_id>/appr/edit/', views.edit_appr, name='edit_appr'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
    path('', include('board.urls')),
    path('photo/', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
    path('deallist/', include('deallist.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('board/', include('board.urls')),
    path('todo/', include('todo.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL) 

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path('', views.Todo_ListView.as_view(), name='plist'),
    path('list/<int:pcode>', views.Todo_ListView.as_view(), name='list'),
    path('insert/<int:pcode>', views.check_post, name='insert'),
    path('save_priority/', views.save_priority, name='save_priority'),
    path('is_complete/', views.is_complete, name='is_complete'),
    path('is_non_complete/', views.is_non_complete, name='is_non_complete'),
    path('detail/<int:pk>', views.Todo_DetailView.as_view(), name='detail'),
    path('update/<int:pk>', views.Todo_UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.Todo_DeleteView.as_view(), name='delete'),
]

board/models.py
from django.db import models
from django.db.models import Q
from django.urls import reverse

#from accounts.models import Account
from django.conf import settings
from django.utils.translation import gettext_lazy as _

from core.models import TimeStampedModel

class Board(models.Model):
    def __str__(self):
        return 'Board Name: ' + self.name

    def get_absolute_url(self):
        return reverse('board:post_list', args=[self.slug])

    slug = models.CharField(default='', unique=True, max_length=100)
    name = models.CharField(default='', max_length=100)
    posts_chunk_size = models.IntegerField(default=10)
    post_pages_nav_chunk_size = models.IntegerField(default=10)
    comments_chunk_size = models.IntegerField(default=5)
    comment_pages_nav_chunk_size = models.IntegerField(default=10)

    is_approval = models.BooleanField(default=False)


class PostQuerySet(models.QuerySet):
    def search(self, search_flag, query):
        if search_flag == 'TITLE':
            return self.filter(title__contains=query)
        elif search_flag == 'CONTENT':
            return self.filter(content__contains=query)
        elif search_flag == 'BOTH':
            return self.filter(Q(title__contains=query) | Q(content__contains=query))
        else:
            return self.all()

    def remain(self):
        return self.filter(is_deleted=False)

    def board(self, board):
        return self.filter(board=board)


class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)

    def search(self, search_flag, query):
        return self.get_queryset().search(search_flag, query)

    def remain(self):
        return self.get_queryset().remain()

    def board(self, board):
        return self.get_queryset().board(board)


class Post(TimeStampedModel):
    def __str__(self):
        return 'Post Title: ' + self.title

    SEARCH_FLAG = [
        ('TITLE', '제목'),
        ('CONTENT', '내용'),
        ('BOTH', '제목+내용')
    ]

    objects = PostManager()

    title = models.CharField(blank=False, max_length=100)
    content = models.TextField(default='')
    board = models.ForeignKey(Board, null=True, on_delete=models.DO_NOTHING)
    is_deleted = models.BooleanField(default=False)
    page_view_count = models.IntegerField(default=0)
    like_count = models.IntegerField(default=0)
    account = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.DO_NOTHING)
    ip = models.GenericIPAddressField(null=True, default='')

    def get_absolute_url(self):
        return reverse('board:view_post', args=[self.id])


class EditedPostHistory(TimeStampedModel):
    post = models.ForeignKey(Post, null=False, default=None, on_delete=models.CASCADE)
    title = models.CharField(default='', max_length=100)
    content = models.TextField(default='')
    ip = models.GenericIPAddressField(null=True, default='')


class Attachment(models.Model):
    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE)
    editedPostHistory = models.ForeignKey(EditedPostHistory, null=True, default=None,
        on_delete=models.CASCADE)
    attachment = models.FileField(blank=True, null=True)


class Comment(TimeStampedModel):
    content = models.TextField(default='')
    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE)
    is_deleted = models.BooleanField(default=False)
    account = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.DO_NOTHING)
    ip = models.GenericIPAddressField(null=True, default='')


class Approval(TimeStampedModel):
    def __str__(self):
        return self.account.__str__()

    class ApprLine(models.TextChoices):
        APPROVAL = 'A', _('결재')
        AGREEMENT = 'B', _('합의')
        RECEIVE = 'R', _('수신')
        CARBONCOPY = 'C', _('참조')

    class ApprState(models.TextChoices):
        NOTYET = 'NY', _('대기')
        ACCEPT = 'AC', _('승인')
        RETURN = 'RT', _('반려')
    
    PostState = [
        ('draft', (
            ('dd', '상신된'),
            ('dc', '완료된'),
            ('dt', '저장된'),
            ('dr', '반려된'),
            ('dn', '반송된'),
            ('de', '회수된')
        )),
        ('approval', (
            ('ab', '결재전'),
            ('ai', '진행중'),
            ('ac', '완료된'),
            ('ar', '반려된')
        )),
        ('referrnece',(
            ('rb', '수신전'),
            ('rc', '완료된')  
        )),
        ('cc', '참조')
    ]

    post = models.ForeignKey(Post, null=True, on_delete=models.CASCADE)
    account = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.DO_NOTHING)
    appr_line = models.CharField(max_length=1, choices=ApprLine.choices, default=ApprLine.APPROVAL)
    appr_priority = models.IntegerField(default=0)
    appr_state = models.CharField(max_length=2, choices=ApprState.choices, default=ApprState.NOTYET)

board/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET
from django.urls import reverse
from django.db.models import F
from django.contrib.auth.decorators import login_required

from board.models import Post, Board, Comment, EditedPostHistory, Attachment, Approval
#from accounts.models import Account
from board.forms import PostForm, AttachmentForm
from core.utils import get_pages_nav_info, get_ip

@require_GET
@login_required
def home(request):
    boards = Board.objects.all()

    data = []
    for board in boards:
        data.append({
            'board': board,
            'recent_posts': Post.objects.board(board).remain().order_by('-id')[:5]
        })
    return render(request, 'board/home.html', {'home_data': data})

@login_required
def new_post(request, board_slug):
    board = Board.objects.get(slug=board_slug)
    if request.method == 'POST':
        post_form = PostForm(request.POST)
        attachment_form = AttachmentForm(request.POST, request.FILES)
        if post_form.is_valid() and attachment_form.is_valid() and request.user.is_authenticated:
            post = post_form.save(commit=False)
            post.board = board
            post.ip = get_ip(request)
            try:
                post.account = request.user
            except Post.DoesNotExist:
                post.account = None
            post.save()
            attachment = attachment_form.save(commit=False)
            attachment.post = post
            attachment.save()
            return redirect(board)
    else:
        post_form = PostForm()
        attachment_form = AttachmentForm()

    return render(request, 'board/new_post.html', {'board': board, 'post_form': post_form, 
        'attachment_form': attachment_form})

@login_required
@require_GET
def post_list(request, board_slug, appr_type='all'):
    board = Board.objects.get(slug=board_slug)

    # search
    search_info = {
        'query': request.GET.get('query', ''),
        'selected_flag': request.GET.get('search_flag', 'TITLE'),
        'flags': Post.SEARCH_FLAG
    }

    if board.is_approval and appr_type != 'all':
        posts = get_appr_list(request, appr_type)
    else:
        if search_info['query']:
            posts = Post.objects.board(board).remain().search(search_info['selected_flag'], 
                search_info['query']).order_by('-id')
        else:
            posts = Post.objects.board(board).remain().order_by('-id')

    # pagination
    paginator = Paginator(posts, board.posts_chunk_size)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    pages_nav_info = get_pages_nav_info(posts, nav_chunk_size=board.post_pages_nav_chunk_size)

    return render(request, 'board/post_list.html', {
        'posts': posts,
        'board': board,
        'pages_nav_info': pages_nav_info,
        'search_info': search_info
    })

@login_required
@require_GET
def view_post(request, post_id):
    non_sliced_query_set = Post.objects.filter(id=post_id)
    non_sliced_query_set.update(page_view_count=F('page_view_count') + 1)

    post = Post.objects.get(id=post_id)
    try:
        attachment = Attachment.objects.get(post=post)
        uploaded_file = attachment.attachment
    except Attachment.DoesNotExist:
        uploaded_file = None

    comments_all_list = Comment.objects.filter(post=post, is_deleted=False).order_by('-id')

    is_modified = False
    history = EditedPostHistory.objects.filter(post=post)
    if history:
        is_modified = True

    paginator = Paginator(comments_all_list, post.board.comments_chunk_size)
    page = request.GET.get('page')
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        comments = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        comments = paginator.page(paginator.num_pages)

    pages_nav_info = get_pages_nav_info(comments,
        nav_chunk_size=post.board.comment_pages_nav_chunk_size)

    is_authenticated = False
    if post.account == request.user or request.user.is_superuser:
        is_authenticated = True

    is_approval = post.board.is_approval
    appr_list = []
    if is_approval:
        appr_list = Approval.objects.filter(post=post).order_by('appr_priority')

    # search
    appr_info = {
        'query': request.GET.get('query', ''),
        'selected_flag': request.GET.get('search_flag', 'TITLE'),
        'flags': Approval.ApprState.choices
    }

    return render(request, 'board/view_post.html', {
        'post': post,
        'uploaded_file': uploaded_file,
        'is_modified': is_modified,
        'comments': comments,
        'pages_nav_info': pages_nav_info,
        'is_authenticated': is_authenticated,
        'is_approval': is_approval,
        'appr_list': appr_list,
        'appr_info': appr_info,
    })

@login_required
@require_GET
def comment_list(request, post_id):
    post = Post.objects.get(id=post_id)
    comments_all_list = Comment.objects.filter(post=post, is_deleted=False).order_by('-id')

    paginator = Paginator(comments_all_list, post.board.comments_chunk_size)
    page = request.GET.get('page')

    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        comments = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        comments = paginator.page(paginator.num_pages)

    pages_nav_info = get_pages_nav_info(comments,
        nav_chunk_size=post.board.comment_pages_nav_chunk_size)

    return render(request, 'board/comment_list.html', {
        'post': post,
        'comments': comments,
        'pages_nav_info': pages_nav_info
    })

@login_required
@require_GET
def post_history_list(request, post_id):
    post = Post.objects.get(id=post_id)
    post_histories = EditedPostHistory.objects.filter(post=post).order_by('-id')
    history_list = []
    for history in post_histories:
        try:
            attachment = Attachment.objects.get(editedPostHistory=history)
            uploaded_file = attachment.attachment
        except Attachment.DoesNotExist:
            uploaded_file = None
        history_list.append([history, uploaded_file])

    return render(request, 'board/post_history_list.html', {
        'history_list': history_list,
        'post_id': post_id
    })


@login_required
def edit_post(request, post_id):
    origin_post = Post.objects.get(id=post_id)
    edited_post = Post.objects.get(id=post_id)

    if request.user != origin_post.account and not request.user.is_superuser:
        return redirect('/')

    try:
        origin_attachment = Attachment.objects.get(post=origin_post)
        origin_attachment_name = origin_attachment.attachment.name
    except Attachment.DoesNotExist:
        origin_attachment = None
        origin_attachment_name = ''

    if request.method == 'POST':
        post_form = PostForm(request.POST, instance=edited_post)
        attachment_form = AttachmentForm(request.POST, request.FILES)

        # origin_attachment_name != request.FILES.get('attachment', ''):
        if not origin_attachment and request.FILES.get('attachment', '') != '' or \
                origin_attachment and request.FILES.get('attachment', '') != '' or \
                request.POST.get('attachment-clear', '') == 'on':
            attach_edit = True
        else:
            attach_edit = False

        if origin_post.title != request.POST['title'] or \
                origin_post.content != request.POST['content'] or attach_edit:

            if post_form.is_valid() and attachment_form.is_valid():
                edited_post.save()

                edited_post_history = EditedPostHistory.objects.create(
                    post=origin_post,
                    title=origin_post.title,
                    content=origin_post.content,
                    ip=origin_post.ip
                )
                edited_post_history.save()

                # add attachment
                if not origin_attachment and request.FILES.get('attachment', '') != '':
                    new_attachment = attachment_form.save(commit=False)
                    new_attachment.post = edited_post
                    new_attachment.save()

                # modify attachment
                elif origin_attachment and request.FILES.get('attachment', '') != '' \
                        and origin_attachment_name != request.FILES.get('attachment', ''):
                    origin_attachment.post = None
                    origin_attachment.editedPostHistory = edited_post_history
                    origin_attachment.save()

                    new_attachment = attachment_form.save(commit=False)
                    new_attachment.post = edited_post
                    new_attachment.save()

                # remove attachment
                elif request.POST.get('attachment-clear', '') == 'on':
                    origin_attachment.post = None
                    origin_attachment.editedPostHistory = edited_post_history
                    origin_attachment.save()

                return redirect(edited_post)
        else:
            error_message = "변경 사항이 없습니다"
            return render(request, 'board/edit_post.html', {
                'post': origin_post,
                'post_form': post_form,
                'attachment_form': attachment_form,

board/templates/board/comment_list.html
{% load hide_ip %}

<!DOCTYPE html>
<html>
<head>
    {% include 'head.html' %}
</head>
<body>
{% if comments %}
<div class="panel">
    <div class="panel-body">
        {% for comment in comments %}
        <div class="media comment">
            <div class="media-body">
                <div class="comment-info">
                    <form method="POST" class="delete-comment-form" action="{% url 'board:delete_comment' post.id comment.id %}">
                        {% csrf_token %}
                    </form>
                    <small class="text-muted comment-date">{{ comment.created_time|date:"Y-m-d H:i:s" }}</small>
                    <small class="text-muted comment-ip">{% hide_ip comment.ip %}</small>
                    {% if comment.account == user %}
                        <small class="delete-comment">삭제</small>
                    {% endif %}
                </div>
                {% if comment.account %}
                    <span class="text-primary">{{ comment.account.username }}</span>
                {% else %}
                    <span class="text-primary">익명</span>
                {% endif %}
                <p class="comment-content">
                    {{ comment.content }}
                </p>
            </div>
        </div>
        {% endfor %}
        <div style="margin-top: 10px;">
            {% include 'pagination.html' with pages_nav_info=pages_nav_info query="" %}
        </div>
    </div>
</div>
{% else %}
<p class="no-comment">
    <strong>댓글이 없습니다.</strong>
</p>
{% endif %}

{% if user.is_authenticated %}
<div class="panel">
    <form method="POST" action="{% url 'board:new_comment' post.id %}">
<div class="row">
        {% csrf_token %}
        <div class="col-sm-9">
            <input type="text" id="id_new_comment" name="comment_content" class="form-control"
                   placeholder="Write comment..."/>
        </div>
        <div class="col-sm-3">
            <button type="submit" id="id_new_comment_submit" class="form-control btn btn-primary">댓글 달기</button>
        </div>
</div>
    </form>
</div>
{% else %}
<p class="comment-require-login">
    <strong>댓글을 달기 위해 로그인하세요.</strong>
</p>
{% endif %}
</body>
</html>

board/templates/board/edit_post.html
{% extends 'board/post_input_base.html' %}

{% block title %}글 수정{% endblock %}

{% block header %}글 수정{% endblock %}

{% block form_action_url %}{% url 'board:edit_post' post.id %}{% endblock %}

{% block submit_button_name %}수정{% endblock %}

{% block cancel_url %}{% url 'board:view_post' post.id %}{% endblock %}

board/templates/board/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% for data in home_data %}
    {% if not forloop.counter|divisibleby:"2" %}
        <div class="row">
    {% endif %}
    <div class="col-md-6">
        <div class="panel panel-post-summary">
            <div class="panel-heading">
                <a href="{% url 'board:post_list' data.board.slug %}">{{ data.board.name }}</a>
            </div>
            <div class="panel-body">
                <table class="table table-hover">
                    <tbody>
                        {% for post in data.recent_posts %}
                            <tr>
                                <td><a href="{% url 'board:view_post' post.id %}">{{ post.title|truncatechars:40 }}</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% if forloop.counter|divisibleby:"2" %}
        </div>
    {% endif %}
{% endfor %}
{% endblock %}

board/templates/board/new_post.html
{% extends 'board/post_input_base.html' %}

{% block title %}글 쓰기{% endblock %}

{% block header %}글 쓰기{% endblock %}

{% block form_action_url %}{% url 'board:new_post' board.slug %}{% endblock %}

{% block submit_button_name %}등록{% endblock %}

{% block cancel_url %}{% url 'board:post_list' board.slug %}{% endblock %}

board/templates/board/pagination.html
{% load url_parameter %}

<nav class="page-nav" aria-label="Page navigation">
    <ul class="pagination justify-content-center pagination-sm">
        {% if pages_nav_info.pre_nav_page != -1 %}
            <li class="page-item">
                {% if search_info.query != "" %}
                <a class="page-link" href="{% url_parameter page=pages_nav_info.pre_nav_page search_flag=search_info.selected_flag query=search_info.query %}">Previous</a>
                {% else %}
                <a class="page-link" href="{% url_parameter page=pages_nav_info.pre_nav_page %}">Previous</a>
                {% endif %}
            </li>
        {% else %}
            <li class="page-item disabled"><a class="page-link">Previous</a></li>
        {% endif %}

        {% for page_num in pages_nav_info.page_list %}
            {% if page_num == pages_nav_info.current_page_num %}
                <li class="page-item disabled current-page-num"><a class="page-link">{{ page_num }}</a></li>
            {% else %}
                <li class="page-item other-page-num">
                    {% if search_info.query != "" %}
                    <a class="page-link" href="{% url_parameter page=page_num search_flag=search_info.selected_flag query=search_info.query %}">{{ page_num }}</a>
                    {% else %}
                    <a class="page-link" href="{% url_parameter page=page_num %}">{{ page_num }}</a>
                    {% endif %}
                </li>
            {% endif %}
        {% endfor %}

        {% if pages_nav_info.next_nav_page != -1 %}
            <li class="page-item">
                {% if search_info.query != "" %}
                <a class="page-link" href="{% url_parameter page=pages_nav_info.next_nav_page search_flag=search_info.selected_flag query=search_info.query %}">Next</a>
                {% else %}
                <a class="page-link" href="{% url_parameter page=pages_nav_info.next_nav_page %}">Next</a>
                {% endif %}
            </li>
        {% else %}
            <li class="page-item disabled"><a class="page-link">Next</a></li>
        {% endif %}
    </ul>
</nav>

board/templates/board/post_list.html
{% extends 'base.html' %}

{% block title %}{{ board.name }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h3>{{ board.name }}</h3>
        <div class="panel panel-default">
            <div class="panel-body">
                <table id="id_post_list_table" class="table table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th class="table-title">제목</th>
                            <th>날짜</th>
                            <th>추천</th>
                            <th>조회 수</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in posts %}
                            <tr>
                                <td>{{ post.id }}</td>
                                <td><a href="{% url 'board:view_post' post.id %}">{{ post.title }}</a></td>
                                <td>{{ post.created_time|date:"Y-m-d H:i:s" }}</td>
                                <td>{{ post.like_count }}</td>
                                <td class="page-view-count">{{ post.page_view_count }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                {% include 'board/pagination.html' with pages_nav_info=pages_nav_info search_info=search_info %}
            </div>
        </div>

        <!-- pagination -->
        <div class="row">
            <div class="col-sm-10">
            <form method="GET" class="form-inline">
                <select name="search_flag" class="form-control search-flag">
                    {% for key, value in search_info.flags %}
                        <option value="{{ key }}"
                                {% if search_info.selected_flag == key %} selected {% endif %}>{{ value }}</option>
                    {% endfor %}
                </select>
                <div class="input-group">
                    <input type="text" class="form-control" name="query"
                       placeholder="검색어 입력" value="{{search_info.query}}">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-default btn-search">
                            <i class="bi bi-search"></i>
                        </button>
                    </span>
                </div>
            </form>
            </div>
            <div class="col-sm-2">
                <a id="id_create_post_button" class="form-control btn btn-primary redirection-button"
                        href="{% url 'board:new_post' board.slug %}">글쓰기</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board/templates/board/view_post.html
{% extends 'base.html' %}
{% load hide_ip %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default post-panel">
            <div class="panel-heading">
                <span class="panel-title">{{ post.title }}</span>
                <div class="post-info">
                    {% if is_modified and is_authenticated %}
                        <span id="post_history"><a href="{% url 'board:post_history_list' post.id%}">수정 내역</a></span>
                    {% endif %}
                    {% if post.account %}
                        <span class="text-muted">작성자: {{ post.account.username }}</span>
                    {% endif %}
                    <span class="text-muted" id="id_page_view_count">조회수: {{ post.page_view_count }}</span>
                    <span class="text-muted" id="id_post_ip">IP:{% hide_ip post.ip %} </span>
                    <span class="text-muted">날짜: {{ post.created_time|date:"Y-m-d H:i:s" }}</span>
                </div>
            </div>
            <!-- Approval -->
            {% if is_approval %}
                <div class="panel-approval">
                    <div class="row">
                        {% for appr in appr_list %}
                            <div class="col col-md-2">{{appr.get_appr_line_display}}:{{appr.account.username}}</div>
                        {% endfor %}
                        <div class="col"></div>
                    </div>
                    <form  class="row" method="POST" action="{% url 'board:edit_appr' post.id%}">
                        {% for appr in appr_list %}
                            <div class="col col-md-2">
                                <select name="appr_state-{{appr.id}}" class="form-select appr-state" {% if appr.account.username != request.user.username %}Disabled{% endif %}>
                                {% for key, value in appr_info.flags %}
                                <option value="{{ key }}"
                                    {% if appr.appr_state == key %} selected {% endif %}>{{ value }}</option>
                                {% endfor %}
                                </select>
                            </div>
                        {% endfor %}
                        <div class="col col-md-2">
                            {% csrf_token %}
                            <button id="id_edit_appr_button" type="submit" class="form-control btn btn-primary">결재</button>
                        </div>
                    </form>
                </div>
            {% endif %}
            <div class="panel-body" >
                {{ post.content|safe }}
            </div>
            {% if uploaded_file %}
                <div class="panel-footer">
                    <a id="id_uploaded_file" href="{{ uploaded_file.url }}" download>{{ uploaded_file.name }}</a>
                </div>
            {% endif %}
        </div>
        <div class="text-center form-inline">
            <button class="form-control btn btn-primary like-button" post-id="{{ post.id }}">
                <span class="like-count">{{ post.like_count }}</span>
                &nbsp;<i class="bi bi-hand-thumbs-up"></i>&nbsp;추천!
            </button>
        </div>


        <!-- comment -->
        <h3>댓글</h3>
        <div class="row">
            <iframe src="{% url 'board:comment_list' post.id %}" class="comment-iframe" scrolling="no"></iframe>
        </div>
        <br/>
        <div class="row">
            <div class="col-sm-4">
                <button id="id_back_to_post_list_button" class="form-control btn btn-default redirection-button"
                        path="{% url 'board:post_list' post.board.slug %}">목록</button>
            </div>
            {% if is_authenticated %}
            <div class="col-sm-4">
                <button id="id_edit_post_button" class="form-control btn btn-default redirection-button"
                            path="{% url 'board:edit_post' post.id %}">수정</button>
            </div>
            <div class="col-sm-4">
                <form method="POST" action="{% url 'board:delete_post' post.id %}">
                    {% csrf_token %}
                    <button id="id_delete_post_button" type="submit" class="form-control btn btn-danger">삭제</button>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}