config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
    path('', include('board.urls')),
    path('photo/', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
    path('deallist/', include('deallist.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('board/', include('board.urls')),
    path('todo/', include('todo.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL) 

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path('', views.Todo_ListView.as_view(), name='plist'),
    path('list/<int:pcode>', views.Todo_ListView.as_view(), name='list'),
    path('insert/<int:pcode>', views.check_post, name='insert'),
    path('save_priority/', views.save_priority, name='save_priority'),
    path('is_complete/', views.is_complete, name='is_complete'),
    path('is_non_complete/', views.is_non_complete, name='is_non_complete'),
    path('detail/<int:pk>', views.Todo_DetailView.as_view(), name='detail'),
    path('update/<int:pk>', views.Todo_UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.Todo_DeleteView.as_view(), name='delete'),
]

todo/models.py
from django.db import models
from django.db.models import Max
from django.conf import settings

# Create your models here.
class TodoProject(models.Model):
    pname = models.CharField(max_length=100)
    account = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.pname

class TodoList(models.Model):
    pcode = models.ForeignKey(TodoProject, on_delete=models.CASCADE)
    title = models.CharField(blank=False, max_length=100)
    content = models.TextField(default='')
    is_complete = models.BooleanField(default=False)
    priority = models.IntegerField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title
    
    def todo_save(self):
        self.is_complete = False
        if TodoList.objects.filter(pcode=self.pcode).aggregate(Max('priority'))['priority__max'] is None:
            self.priority = 1
        else:
            self.priority = int(TodoList.objects.filter(pcode=self.pcode).latest('priority').priority) + 1
        self.save()

    def todo_update(self, complete):
        self.is_complete = complete
        self.save()

todo/forms.py
from django import forms
from deallist.widgets import DatePickerWidget

from .models import TodoList

class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ('title', 'content', 'end_date')
        widgets = {
            'end_date' : DatePickerWidget
        }

todo/views.py
from datetime import datetime
import json
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.http import JsonResponse

from .models import TodoList, TodoProject
from .forms import TodoForm

# Create your views here.
class Todo_ListView(generic.TemplateView):
    def get(self, request, *args, **kwargs):
        if kwargs.__contains__('pcode'):
            pcode = int(kwargs['pcode'])
        else:
            pcode = 1
        
        template_name = 'todo/todo_list.html'
        # 기한 없는 일정
        todo_list_no_endDate = TodoList.objects.filter(pcode=pcode,end_date__isnull=True, is_complete=0).\
            order_by('priority')
        # 기한 있고 마감이 안된 일정
        todo_list_endDate_non_complete = TodoList.objects.filter(pcode=pcode,end_date__isnull=False, is_complete=False).\
            order_by('priority')
        # 마감 된 일정
        todo_list_endDate_complete = TodoList.objects.filter(pcode=pcode,is_complete=True).order_by('priority')
        today = datetime.now()

        close_end_day, over_end_day = [],[]
        for i in todo_list_endDate_non_complete:
            e_day = str(i.end_date).split('-')
            end_day = datetime(int(e_day[0]), int(e_day[1]), int(e_day[2]))
            if (end_day - today).days < -1: 
                over_end_day.append(i.title)
            if (end_day - today).days >= -1 and (end_day - today).days < 3: 
                close_end_day.append(i.title)
        
        return render(request, template_name, {
            'todo_list_endDate_non_complete': todo_list_endDate_non_complete,
            'todo_list_endDate_complete': todo_list_endDate_complete,
            'todo_list_no_endDate': todo_list_no_endDate,
            'close_end_day': close_end_day,
            'over_end_day': over_end_day,
            'pcode': pcode,
        })

class Todo_DetailView(generic.DetailView):
    model = TodoList
    template_name = 'todo/todo_detail.html'
    context_object_name = 'todo_list'

class Todo_UpdateView(generic.UpdateView):
    model = TodoList
    template_name = "todo/todo_update.html"
    form_class = TodoForm

    def get_success_url(self):
        return reverse_lazy('doto:list', kwargs={'pcode': self.object.pcode.id })

    def form_valid(self, form):
        form.save()
        return render(self.request, 'todo/todo_success.html', {
            'message': '일정을 업데이트 했습니다', 'pcode': self.object.pcode.id})

class Todo_DeleteView(generic.DeleteView):
    model = TodoList
    success_url = '/todo/'
    context_object_name = 'todo_list'
    template_name = "todo/todo_confirm_delete.html"

def check_post(request, pcode):
    template_name = 'todo/todo_success.html'
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            message = '일정을 추가하였습니다'
            if len(request.POST.get('title')) < 2:
                message = '제목은 2글자 이상으로 입력해주세요'
            else:
                todo = form.save(commit=False)
                todo.pcode = TodoProject.objects.get(id=pcode)
                todo.todo_save()
            return render(request, template_name, {'message': message, 'pcode': pcode})
    else :
        template_name = 'todo/todo_insert.html'
        form = TodoForm
        return render(request, template_name, {'form': form, 'pcode': pcode})

    return render(request, template_name)

def save_priority(reqeust):
    todo_list = json.loads(reqeust.POST['todo_dict'])
    for key, value in todo_list.items():
        if key == "None":
            continue
        todo_selected = TodoList.objects.get(id=key)
        todo_selected.priority = value
        todo_selected.save()
    return JsonResponse({'text': '저장되었습니다'})

def is_complete(request):
    pk = request.POST['data']
    return JsonResponse(checkbox_event(pk, True))

def is_non_complete(request):
    pk = request.POST['data']
    return JsonResponse(checkbox_event(pk, False))

def checkbox_event(pk, is_check):
    todo_selected = TodoList.objects.get(id=pk)
    if is_check:
        todo_selected.is_complete = True
        todo_selected.priority = None
    else :
        todo_selected.is_complete = False
    
    todo_selected.save()
    return_value = {'text': '저장되었습니다'}
    return return_value

todo/templates/todo/todo_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<section id="blog">
  <div class="container">
   <form method="POST" class="post-form">
       {%csrf_token%}

       <p>정말로 {{ todo_list.title }} 일정을 삭제하시나요?</p>
       <input type="submit" class="save btn btn-default" value="Confirm"/>
   </form>
  </div>
</section>

{% endblock content %}

todo/templates/todo/todo_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section id="blog">
  <div class="container">
    <table class="table table-bordered">
          <thead>
            <tr>
              <th>제목</th>
              <th>내용</th>
              <th>마감일</th>
            </tr>
          </thead>
        <tbody>
          <tr>
            <td>{{ todo_list.title }}</td>
            <td>{{ todo_list.content }}</td>
            <td>{{ todo_list.end_date }}</td>
          </tr>
        </tbody>
    </table>
    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'todo:update' pk=todo_list.id %} '">수정</button>
    <button type="button" class="btn btn-primary" onclick="location.href='{% url 'todo:delete' pk=todo_list.id %} '">삭제</button>
  </div>
</section>

{% endblock %}

todo/templates/todo/todo_head.html
{% load static %}
    <script src="{% static 'js/Sortable.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
    <script>
        new Sortable(todo_list_endDate, {
            animation: 150,
            ghostClass: 'blue-background-class'
        });
        new Sortable(todo_list_no_endDate, {
            animation: 150,
            ghostClass: 'blue-background-class'
        });


    </script>

    <script>
        function prioirty_save(){
            todo_list = $(".list-group-item");
            todo_dict = {}
            for(var i = 0 ; i < todo_list.length ; i++){
                todo_dict[todo_list[i].getAttribute("div_pk")] = i + 1
            }
            console.log(todo_dict);
            $.ajax({
              type: "POST",
              url: "{% url 'todo:save_priority' %}",
              data: {'todo_dict': JSON.stringify(todo_dict), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
              dataType: "json",
              success: function(response){
                console.log("성공");
                window.location.href = "{% url 'todo:list' pcode=pcode %}"
              },
              error: function(request, status, error){
                console.log("실패.");
              },
            });
        }
    </script>

    <script>
        completed = document.getElementsByName('complete');
        for(var i = 0; i < completed.length ; i++){
            completed[i].checked = true;
        }

        $("input[name*=complete]").change(function(){
            if($(this).is(":checked")){
                pk = $(this).attr("pk");
                $.ajax({
                  type: "POST",
                  url: "{% url 'todo:is_complete' %}",
                  data: {'data': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                  dataType: "json",
                  success: function(response){
                    console.log("성공");
                    window.location.href = "{% url 'todo:list' pcode=pcode %}"
                  },
                  error: function(request, status, error){
                    console.log("실패.");
                  },
                });
            }
            //체크박스 해제
            else{
                pk = $(this).attr("pk");
                $.ajax({
                  type: "POST",
                  url: "{% url 'todo:is_non_complete' %}",
                  data: {'data': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                  dataType: "json",
                  success: function(response){
                    window.location.href = "{% url 'todo:list' pcode=pcode %}"
                  },
                  error: function(request, status, error){
                    console.log("실패.");
                  },
                });
            }
        });

    </script>

todo/templates/todo/todo_insert.html
  
{% extends 'base.html' %}
{% block content %}
{{form.media}}
<div class="col-md-12">
    <div class="container">
        <form method="POST" class="post-form" action="{% url 'todo:insert' pcode=pcode %}">
           {%csrf_token%}
           {{form.as_p}}
           <button type="submit" class="save btn btn-default">Save</button>
       </form>
    </div>

</div>

{% endblock content %}

todo/templates/todo/todo_list.html
{% extends 'base.html' %}
{% block title %}Todo List{% endblock %}

{% block content %}

<div class="row">
<div class="alert alert-info">
    <strong>마감이 지난 일정!</strong> {{ over_end_day }}
</div>
<div class="alert alert-info">
    <strong>마감이 가까운 일정!</strong> {{ close_end_day }}
</div>
<div class="col-md-4">
    <div class="container">
        <h2>기한 있는 일정</h2><br>
        <div id="todo_list_endDate" class="list-group col">
            {% for list in todo_list_endDate_non_complete %}
            <div class="list-group-item" div_pk={{list.id}} priority={{list.priority}}><input type="checkbox" pk={{list.id}} name="end_non_complete" value={{list.title}}> <a href="{% url 'todo:detail' pk=list.id %}">{{list.title}}</a><p>{{list.end_date}}</p></div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="container">
        <h2>기한 없는 일정</h2><br>
        <div id="todo_list_no_endDate" class="list-group col">
        {% with end_date="마감일 없음" %}
            {% for list in todo_list_no_endDate %}
            <div class="list-group-item" div_pk={{list.id}}><input type="checkbox" pk={{list.id}} name="no_endDate_non_complete" value={{list.title}}> <a href="{% url 'todo:detail' pk=list.id %}">{{list.title}}</a><p>{{end_date}}</p></div>
            {% endfor %}
        {% endwith %}
        </div>
    </div>
</div>

<div class="col-md-4">
    <div class="container">
        <h2>마감 된 일정</h2><br>
        <div class="list-group col">
            {% with end_date="마감일 없음" %}
                {% for list in todo_list_endDate_complete %}
                    {% if list.end_date == None %}
                        <div class="list-group-item list-group-item-success" div_pk={{list.priority}}><input type="checkbox" pk={{list.id}} name="complete" value={{list.title}}> <a href="{% url 'todo:detail' pk=list.id %}">{{list.title}}</a><p>{{end_date}}</p></div>
                    {% else %}
                        <div class="list-group-item list-group-item-success" div_pk={{list.priority}}><input type="checkbox" pk={{list.id}} name="complete" value={{list.title}}> <a href="{% url 'todo:detail' pk=list.id %}">{{list.title}}</a><p>{{list.end_date}}</p></div>
                    {% endif %}
                {% endfor %}
            {% endwith %}
        </div>
    </div>
</div>

<div class="col-md-12">
      <button type="button" class="btn btn-primary" onclick="location.href='{% url 'todo:insert' pcode=pcode %} '">
            일정추가
      </button>
      <button type="button" class="btn btn-primary" onclick="prioirty_save()">
            *우선순위 저장
      </button>
      <p>* 마우스 드래그로 우선순위 변경이 가능합니다</p>
</div>
</div>
{% include 'todo/todo_head.html' %}
{% endblock %}

todo/templates/todo/todo_success.html
<script>
    message = "{{ message }}";
    alert(message);
    window.location.href = "{% url 'todo:list' pcode=pcode %}"
</script>

todo/templates/todo/todo_update.html
{% extends 'base.html' %}
{% block content %}
{{form.media}}
<section id="blog">
  <div class="container">
   <form method="POST" class="post-form">
       {%csrf_token%}
       {{form.as_p}}
       <input type="submit" class="save btn btn-default" value="Update"></input>
   </form>
  </div>
</section>

{% endblock content %}