config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bookmark/', include('bookmark.urls')),
    path('', include('board.urls')),
    path('photo/', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
    path('deallist/', include('deallist.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('board/', include('board.urls')),
    path('todo/', include('todo.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL) 

deallist/urls.py
from django.urls import path
from .views import DealListCreateView, DealListDeleteView, DealListDetailView, \
    DealListListView, DealListUpdateView

app_name = "deallist"
urlpatterns = [
    path('', DealListListView.as_view(), name='list'),
    path('add/', DealListCreateView.as_view(), name='add'),
    path('detail/<int:pk>', DealListDetailView.as_view(), name='detail'),
    path('update/<int:pk>', DealListUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', DealListDeleteView.as_view(), name='delete'),
]

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path('', views.Todo_ListView.as_view(), name='plist'),
    path('list/<int:pcode>', views.Todo_ListView.as_view(), name='list'),
    path('insert/<int:pcode>', views.check_post, name='insert'),
    path('save_priority/', views.save_priority, name='save_priority'),
    path('is_complete/', views.is_complete, name='is_complete'),
    path('is_non_complete/', views.is_non_complete, name='is_non_complete'),
    path('detail/<int:pk>', views.Todo_DetailView.as_view(), name='detail'),
    path('update/<int:pk>', views.Todo_UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.Todo_DeleteView.as_view(), name='delete'),
]

deallist/models.py
import datetime
from django.db import models
#from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class ReceiptList(models.Model):
    receipt_date = models.DateField("접수날짜", default=datetime.datetime.now)
    receipt_user = models.ManyToManyField(settings.AUTH_USER_MODEL)
    company_name = models.CharField("회사명", max_length=100)
    sourcing = models.CharField("Sourcing", max_length=20, null=True)
    company_field = models.CharField("사업영역", max_length=100, null=True)
    memo = models.TextField("메모", blank=True, default="")
    is_invest = models.BooleanField("투자진행", default=False)

    def __str__(self):
        return self.receipt_date.strftime("%Y-%m-%d") + " " + self.company_name

    def get_username(self):
        rname = ''
        for ruser in self.receipt_user.all():
            rname = rname + ruser.username + '/'
        return rname[:-1]


class ReviewList(models.Model):
    receipt_id = models.ForeignKey(ReceiptList, on_delete=models.CASCADE,
        related_name='receipt_review')
    review_user = models.ManyToManyField(settings.AUTH_USER_MODEL)
    review_detail = models.TextField("세부사항", null=True)
    is_acctive = models.BooleanField("진행여부", default=True)

    def __str__(self):
        return self.receipt_id.company_name

deallist/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import ReceiptList
from .widgets import DatePickerWidget

# Must be changed!!
INVEST_CHOICES = [
    ('박영호', '박영호'),
    ('구경모', '구경모'),
    ('박형준', '박형준'),
]

class DealListCreationForm(forms.ModelForm):
    receipt_user = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=INVEST_CHOICES,
    )
    class Meta:
        model = ReceiptList
        fields = '__all__'
        widgets = {
            #'company_name': CounterTextInput,
            'receipt_date': DatePickerWidget,
        }
    
    def clean_receipt_user(self):
        cleaned_data = super().clean()
        ru = []
        for _ru in cleaned_data['receipt_user']:
            ru.append(User.objects.get(username=_ru))
        return ru

deallist/views.py
# deallist/view.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView

from django.urls import reverse_lazy

from .models import ReceiptList
from .forms import DealListCreationForm

# Create your views here.
class DealListListView(ListView):
    model = ReceiptList
    template_name = "deallist/list.html"
    paginate_by = 3
    ordering=['-receipt_date', '-id']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if context['is_paginated']:
            context["min_page"] = min(context['page_obj'].number - 5, context['page_obj'].paginator.num_pages - 10)
            context["max_page"] = max(context['page_obj'].number + 5, 11)
        return context

class DealListCreateView(CreateView):
    model = ReceiptList
    #fields = '__all__'
    success_url = reverse_lazy('deallist:list')
    form_class = DealListCreationForm
    template_name = 'deallist/create.html'


class DealListDetailView(DetailView):
    model = ReceiptList

class DealListUpdateView(UpdateView):
    model = ReceiptList
    #fields = '__all__'
    #template_name_suffix = '_update'
    template_name = 'deallist/create.html'
    success_url = reverse_lazy('deallist:list')
    form_class = DealListCreationForm

class DealListDeleteView(DeleteView):
    model = ReceiptList
    success_url = reverse_lazy('deallist:list')

deallist/templates/deallist/create.html
{% extends 'base.html' %}

{% block title %}DealList Create/Update{% endblock %}

{% block content %}
{{form.media}}

    <form action="" method="POST">
        <table>
            {% csrf_token %}
            {{form.as_table}}
            <tr><td><input type="submit" value="Create/Update DealList" class="btn btn-info btn-sm"></td></tr>
        </table>
    </form>
{% endblock content %}

deallist/templates/deallist/list.html
{% extends 'base.html' %}

{% block title %}DealList List{% endblock %}

{% block content %}
    <div class="btn-group">
        <a href="{% url 'deallist:add' %}" class="btn btn-info">Add Deal</a>
    </div>
    <table class="table table-sm table-hover tss">
        <thead>
            <tr>                
                <th scope="col" class="col">접수일</th>
                <th scope="col" class="col-md-auto">회사명</th>
                <th scope="col" class="col-md-auto">사업영역</th>
                <th scope="col" class="col-md-auto">Memo</th>
                <th scope="col" class="col-md-auto">접수자</th>
                <th scope="col" class="col-md-auto">Sourcing</th>
                <th scope="col" class="col">M</th>
                <th scope="col" class="col">D</th>
            </tr>
        </thead>
        <tbody>
            {% for deal in object_list %}
                <tr class="input-group-mb {% if deal.is_invest %}table-success{% endif %}"">
                    <td>{{ deal.receipt_date|date:"Y년n월w주" }}</td>
                    <td>{{ deal.company_name }}</td>
                    <td>{{ deal.company_field }}</td>
                    <td>{{ deal.memo|linebreaksbr }}</textarea></td>
                    <td>{{ deal.get_username }}</td>
                    <td>{{ deal.sourcing }}</td>
                    <td><a href="{% url 'deallist:update' pk=deal.id %}" class="btn btn-success btn-sm">M</a></td>
                    <td><a href="{% url 'deallist:delete' pk=deal.id %}" class="btn btn-danger btn-sm">D</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block pagination %}
    {% include 'pagination.html' %}
{% endblock %}

deallist/templates/deallist/receiptlist_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <div class="alert alert-danger">Do you want to delete Deal "{{object}}"?</div>
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock content %}

deallist/templates/deallist/receiptlist_update.html
{% extends 'base.html' %}

{% block title %}DealList Modify{% endblock %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" class="btn btn-info btn-sm">
    </form>
{% endblock content %}